apiVersion: v1
kind: Service
metadata:
  name: http-api
  namespace: http-api
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: http-api
