apiVersion: v1
kind: Service
metadata:
  name: reduce-price
  namespace: reduce-price
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: reduce-price
